package report

import (
	"github.com/PinoHouse/works-on-my-whiteboard/internal/content"
	"github.com/PinoHouse/works-on-my-whiteboard/internal/validator"
)

var knownDiagnosticCodes = map[string]struct{}{
	validator.CodeInvalidStableID:             {},
	validator.CodeDuplicateScopeFamily:        {},
	validator.CodeDuplicateScopeCase:          {},
	validator.CodeCaseOutsideScope:            {},
	validator.CodeUnknownFamily:               {},
	validator.CodeUnknownReference:            {},
	validator.CodeDuplicateClaimID:            {},
	validator.CodeInvalidSourceURL:            {},
	validator.CodeInvalidSourceDate:           {},
	validator.CodeDanglingSource:              {},
	validator.CodeCompleteContractEmpty:       {},
	validator.CodeMissingCaseBinding:          {},
	validator.CodeMissingPrincipleBinding:     {},
	validator.CodeDuplicateBindingID:          {},
	validator.CodeDuplicateRequiredRun:        {},
	validator.CodeInvalidRunBinding:           {},
	validator.CodeForeignClaim:                {},
	validator.CodeUnusedBinding:               {},
	validator.CodeBindingWorkloadMismatch:     {},
	validator.CodeUnknownImplementation:       {},
	validator.CodeMissingRequiredPrincipleLab: {},
	validator.CodeMissingRequiredAdapter:      {},
	validator.CodeDependencyIncomplete:        {},
	validator.CodeOrphanedLab:                 {},
	validator.CodeStatusVocabularyMismatch:    {},
	validator.CodeAliasCycle:                  {},
	validator.CodeReleaseScopeIncomplete:      {},
	validator.CodeReleaseFamilyMismatch:       {},
	content.CodeHeadingContractMismatch:       {},
	content.CodeEmptySectionBody:              {},
	content.CodeSectionTooShort:               {},
	content.CodeUnfinishedMarker:              {},
	content.CodeInvalidClaimMarker:            {},
	content.CodeUnknownClaim:                  {},
	content.CodeMissingClaimMarker:            {},
	content.CodeConflictingClaimClass:         {},
	content.CodeAssumptionContextMissing:      {},
	content.CodeMeasuredClaimUnbound:          {},
	content.CodeSourcedClaimInvalid:           {},
	content.CodeMissingContentFile:            {},
	content.CodeInvalidLinkTarget:             {},
	content.CodeMissingLinkTarget:             {},
	content.CodeMissingHeadingFragment:        {},
	content.CodeInvalidUTF8:                   {},
	content.CodeContentReadFailure:            {},
}
